# Generated by Django 6.1.1 on 2026-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
