# Generated by Django 6.1.1 on 2026-10-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_student_delete_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
