# Generated by Django 6.1.1 on 2026-10-01 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_stageoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stageoffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.student')),
            ],
        ),
    ]
