# Generated by Django 6.1.1 on 2026-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
